# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test Segment
#
- hosts: localhost
  become: yes
  tasks:
    - name: Update Segment
      nsxt_policy_segment:
        hostname: "default"
        nsx_cert_path: /root/com.vmware.nsx.ncp/nsx.crt
        nsx_key_path: /root/com.vmware.nsx.ncp/nsx.key
        validate_certs: True
        ca_path: /path/to/my/ca-bundle
        state: present
        domain_name: dn1
        transport_zone_display_name: "1-transportzone-730"
        replication_mode: "SOURCE"
        address_bindings:
          - ip_address: "10.1.2.11"
        advanced_config:
          address_pool_display_name: small-2-pool
          connectivity: "OFF"
          hybrid: False
          local_egress: True
        admin_state: UP
        connectivity_path: "/infra/tier-1s/d082bc25-a9b2-4d13-afe5-d3cecad4b854"
        subnets:
          - gateway_address: "40.1.1.1/16"
        segment_ports:
          - display_name: test-sp-1
            state: present
            tags:
              - scope: "scope-1"
                tag: "tag-2"
            extra_configs:
              - config_pair:
                  key: key
                  value: value
            ignored_address_bindings:
              - ip_address: "10.1.2.122"
          - display_name: test-sp-2
            state: present
          - display_name: test-sp-3
            state: present